version: '3.2'

services:

  php:
    build: docker
    depends_on:
      - mysql
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    working_dir: /app
    ports:
      - "8000:80"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=cusomers
      - MYSQL_USER=root
      - MYSQL_PASSWORD=verysecret
